// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SubscriptionAssistant.Models;

#nullable disable

namespace SubscriptionAssistant.Migrations
{
    [DbContext(typeof(SubscriptionAssistantDbContext))]
    partial class SubscriptionAssistantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SubscriptionAssistant.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Видео и музыкальные платформы",
                            Name = "Стриминговые сервисы"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Подписки на ПО и приложения",
                            Name = "Программное обеспечение"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Хранилища и облачные решения",
                            Name = "Облачные сервисы"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Онлайн-курсы и обучающие платформы",
                            Name = "Образование"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Игровые подписки и сервисы",
                            Name = "Игры"
                        });
                });

            modelBuilder.Entity("SubscriptionAssistant.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 599m,
                            IsSuccessful = true,
                            PaymentDate = new DateTime(2025, 10, 9, 11, 14, 46, 142, DateTimeKind.Utc).AddTicks(4371),
                            SubscriptionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 299m,
                            IsSuccessful = true,
                            PaymentDate = new DateTime(2025, 10, 9, 11, 14, 46, 142, DateTimeKind.Utc).AddTicks(4375),
                            SubscriptionId = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 699m,
                            IsSuccessful = true,
                            PaymentDate = new DateTime(2025, 10, 9, 11, 14, 46, 142, DateTimeKind.Utc).AddTicks(4378),
                            SubscriptionId = 3
                        },
                        new
                        {
                            Id = 4,
                            Amount = 799m,
                            IsSuccessful = true,
                            PaymentDate = new DateTime(2024, 11, 9, 11, 14, 46, 142, DateTimeKind.Utc).AddTicks(4380),
                            SubscriptionId = 4
                        },
                        new
                        {
                            Id = 5,
                            Amount = 2499m,
                            IsSuccessful = true,
                            PaymentDate = new DateTime(2025, 10, 9, 11, 14, 46, 142, DateTimeKind.Utc).AddTicks(4384),
                            SubscriptionId = 5
                        });
                });

            modelBuilder.Entity("SubscriptionAssistant.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 599m,
                            LogoUrl = "/logos/netflix.png",
                            Name = "Netflix"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 299m,
                            LogoUrl = "/logos/spotify.png",
                            Name = "Spotify"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 399m,
                            LogoUrl = "/logos/youtube.png",
                            Name = "YouTube Premium"
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 799m,
                            LogoUrl = "/logos/microsoft.png",
                            Name = "Microsoft 365"
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 2499m,
                            LogoUrl = "/logos/adobe.png",
                            Name = "Adobe Creative Cloud"
                        });
                });

            modelBuilder.Entity("SubscriptionAssistant.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NextPaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BillingCycle = "ежемесячно",
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Мой Netflix Премиум",
                            NextPaymentDate = new DateTime(2025, 11, 24, 11, 14, 46, 142, DateTimeKind.Utc).AddTicks(4148),
                            Price = 599m,
                            ServiceId = 1,
                            StartDate = new DateTime(2025, 9, 9, 11, 14, 46, 142, DateTimeKind.Utc).AddTicks(4138),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BillingCycle = "ежемесячно",
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Spotify Премиум",
                            NextPaymentDate = new DateTime(2025, 11, 14, 11, 14, 46, 142, DateTimeKind.Utc).AddTicks(4157),
                            Price = 299m,
                            ServiceId = 2,
                            StartDate = new DateTime(2025, 5, 9, 11, 14, 46, 142, DateTimeKind.Utc).AddTicks(4156),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            BillingCycle = "ежемесячно",
                            CategoryId = 1,
                            IsActive = true,
                            Name = "YouTube Premium Семейный",
                            NextPaymentDate = new DateTime(2025, 12, 4, 11, 14, 46, 142, DateTimeKind.Utc).AddTicks(4164),
                            Price = 699m,
                            ServiceId = 3,
                            StartDate = new DateTime(2025, 10, 9, 11, 14, 46, 142, DateTimeKind.Utc).AddTicks(4163),
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            BillingCycle = "ежегодно",
                            CategoryId = 2,
                            IsActive = true,
                            Name = "Microsoft 365 Личный",
                            NextPaymentDate = new DateTime(2025, 12, 9, 11, 14, 46, 142, DateTimeKind.Utc).AddTicks(4311),
                            Price = 799m,
                            ServiceId = 4,
                            StartDate = new DateTime(2024, 11, 9, 11, 14, 46, 142, DateTimeKind.Utc).AddTicks(4307),
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            BillingCycle = "ежемесячно",
                            CategoryId = 2,
                            IsActive = true,
                            Name = "Adobe Creative Cloud",
                            NextPaymentDate = new DateTime(2025, 11, 19, 11, 14, 46, 142, DateTimeKind.Utc).AddTicks(4316),
                            Price = 2499m,
                            ServiceId = 5,
                            StartDate = new DateTime(2025, 8, 9, 11, 14, 46, 142, DateTimeKind.Utc).AddTicks(4314),
                            UserId = 4
                        });
                });

            modelBuilder.Entity("SubscriptionAssistant.Models.SubscriptionManager.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 9, 11, 14, 46, 142, DateTimeKind.Utc).AddTicks(4073),
                            Email = "ivanov@example.com",
                            PasswordHash = "hashed_password_1",
                            Username = "иванов"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 9, 11, 14, 46, 142, DateTimeKind.Utc).AddTicks(4076),
                            Email = "petrov@example.com",
                            PasswordHash = "hashed_password_2",
                            Username = "петров"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 9, 11, 14, 46, 142, DateTimeKind.Utc).AddTicks(4078),
                            Email = "sidorova@example.com",
                            PasswordHash = "hashed_password_3",
                            Username = "сидорова"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 11, 9, 11, 14, 46, 142, DateTimeKind.Utc).AddTicks(4081),
                            Email = "kuznetsov@example.com",
                            PasswordHash = "hashed_password_4",
                            Username = "кузнецов"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 11, 9, 11, 14, 46, 142, DateTimeKind.Utc).AddTicks(4084),
                            Email = "smirnov@example.com",
                            PasswordHash = "hashed_password_5",
                            Username = "смирнов"
                        });
                });

            modelBuilder.Entity("SubscriptionAssistant.Models.Payment", b =>
                {
                    b.HasOne("SubscriptionAssistant.Models.Subscription", "Subscription")
                        .WithMany("Payments")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("SubscriptionAssistant.Models.Subscription", b =>
                {
                    b.HasOne("SubscriptionAssistant.Models.Category", "Category")
                        .WithMany("Subscriptions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubscriptionAssistant.Models.Service", "Service")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubscriptionAssistant.Models.SubscriptionManager.Models.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SubscriptionAssistant.Models.Category", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("SubscriptionAssistant.Models.Service", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("SubscriptionAssistant.Models.Subscription", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SubscriptionAssistant.Models.SubscriptionManager.Models.User", b =>
                {
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
